name: "Build"
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: "Clojure Tests"
        run: clojure -A:dev:test
